### ISSUE TITLE
Import into Eclipse

### ISSUE THREAD

**Issue by BinEP** [Team-2502/RobotCode2017#1]
No one that has taken java at the high school will be able to use this project because it can't be directly imported into eclipse. They aren't taught gradle or anything. Should switch to direct import. Also, might consider making a "Develop" branch for code that needs to be tested. And a master branch that has code that has been pushed to the robot. Last year, things did not go well when code wasn't save to github that was used and wasn't labeled at all. Or saved on personal laptops instead on the team one or on github and clearly labelled

**Comment by vandench** [comment]
1.) just changed README.md to explain how to use gradle for setup (it's quick, short, and simple).
2.) Haven't gotten around to adding a 'Develop' branch, but the repository is setup so that you have to push to another branch before you can merge into master. Also it has to be approved by Travis CI (which basically verifies that the code compiles, that is also what the file '.travis.yml' is for).

**Comment by vandench** [comment]
Added 'Develop' branch.

**Comment by BinEP** [comment]
Cool

**Comment by vandench** [comment]
Should also mention that if you look at '.gitignore' you will see that it ignores IDE specific files and folders, this ensure better compatibility between user and it's not that hard to regenerate them.

**Comment by vandench** [comment]
Also I didn't want to use Gradle (I might have used it on my own but I wouldn't have forced it onto others) but for Travis CI to work properly it needed a build script and this was the simplest option.
